name: React App Deployment # name of the workflo

on:
  push:
    branches:
      - deploy-footbet # branch name

permissions:
  contents: write

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    env:
      REACT_APP_UPLOAD_URL: https://footbet.herokuapp.com/uploads
      REACT_APP_API_URL: https://footbet.herokuapp.com/

    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v2

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '18.16.1'

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # install dependencies
      - name: Install dependencies
        run: npm i

      # build the react app
      - name: Build
        run: npm run build

      # deploy the react app to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # NOTE: ACTIONS_DEPLOY_ACCESS_TOKEN is a secret token that is automatically generated by GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # directory to deploy
